services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pluff
      POSTGRES_PASSWORD: pluff
      POSTGRES_DB: pluff
    ports:
      - "5432:5432"
    volumes:
      - pluff-postgres:/var/lib/postgresql/data

volumes:
  pluff-postgres:

